favicon: https://cdn.jsdelivr.net/gh/gaoyanliang/blogImgs@main/blog/img/icon.svg
banner: https://gitee.com/Langwenchong/figure-bed/raw/master/uugai.com_1626063299631.png

logo:
  expanded: https://gitee.com/Langwenchong/figure-bed/raw/master/uugai.com_1626063299631.png
  collapsed: https://gitee.com/Langwenchong/figure-bed/raw/master/uugai.com-1626063308478.png
  dark: https://gitee.com/Langwenchong/figure-bed/raw/master/uugai.com_1626097409216.png

flag:
  icon: flag-cn
  name: Chinese

search: true

githubCorner: '<a href="https://github.com/gaoyanliang/navigation" class="github-corner" aria-label="View source on GitHub"><svg width="80" height="80" viewBox="0 0 250 250" style="fill:#151513; color:#fff; position: absolute; top: 0; border: 0; right: 0;" aria-hidden="true"><path d="M0,0 L115,115 L130,115 L142,142 L250,250 L250,0 Z"></path><path d="M128.3,109.0 C113.8,99.7 119.0,89.6 119.0,89.6 C122.0,82.7 120.5,78.6 120.5,78.6 C119.2,72.0 123.4,76.3 123.4,76.3 C127.3,80.9 125.5,87.3 125.5,87.3 C122.9,97.6 130.6,101.9 134.4,103.2" fill="currentColor" style="transform-origin: 130px 106px;" class="octo-arm"></path><path d="M115.0,115.0 C114.9,115.1 118.7,116.5 119.8,115.4 L133.7,101.6 C136.9,99.2 139.9,98.4 142.2,98.6 C133.8,88.0 127.5,74.4 143.8,58.0 C148.5,53.4 154.0,51.2 159.7,51.0 C160.3,49.4 163.2,43.6 171.4,40.1 C171.4,40.1 176.1,42.5 178.8,56.2 C183.1,58.6 187.2,61.8 190.9,65.4 C194.5,69.0 197.7,73.2 200.1,77.6 C213.8,80.2 216.3,84.9 216.3,84.9 C212.7,93.1 206.9,96.0 205.4,96.6 C205.1,102.4 203.0,107.8 198.3,112.5 C181.9,128.9 168.3,122.5 157.7,114.1 C157.9,116.9 156.7,120.9 152.7,124.9 L141.0,136.5 C139.8,137.7 141.6,141.9 141.8,141.8 Z" fill="currentColor" class="octo-body"></path></svg></a><style>.github-corner:hover .octo-arm{animation:octocat-wave 560ms ease-in-out}@keyframes octocat-wave{0%,100%{transform:rotate(0)}20%,60%{transform:rotate(-25deg)}40%,80%{transform:rotate(10deg)}}@media (max-width:500px){.github-corner:hover .octo-arm{animation:none}.github-corner .octo-arm{animation:octocat-wave 560ms ease-in-out}}</style>'

menu:
  - name: ç¨‹åºçŒ¿ğŸ™ˆ
    icon: far fa-star
    submenu:
      - name: ç¼–ç¨‹å·¥å…·
        icon: fas fa-box
        config: warehouse
      - name: åˆ·é¢˜ç½‘ç«™
        icon: fas fa-coffee
        config: oj
      - name: ç«™é•¿å·¥å…·
        icon: fas fa-drafting-compass
        config: blog
      - name: å›¾æ ‡åº“
        icon: fas fa-box-open
        config: open-warehouse
  - name: å¸¸ç”¨å·¥å…·
    icon: far fa-star
    submenu:
      - name: å‚è€ƒæ–‡æ¡£
        icon: fas fa-book
        config: books
      - name: å›¾åºŠå·¥å…·
        icon: fas fa-images
        config: imagebeds
      - name: æ”¶è—å·¥å…·
        icon: fas fa-share
        config: tools
      - name: æ–‡ä»¶å¤„ç†
        icon: fas fa-briefcase
        config: files
  - name: è®¾è®¡ç¾åŒ–
    icon: fas fa-star
    submenu:
      - name: é¢œè‰²æ­é…
        icon: fas fa-paint-brush
        config: colors
      - name: å›¾ç‰‡ç´ æ
        icon: fas fa-camera-retro
        config: images

# ====================================== ç¨‹åºçŒ¿ğŸ™ˆ ======================================

warehouse:
  - name: github
    url: https://github.com/
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/github.png
    description: æ˜¯ä¸ªç¨‹åºçŒ¿å°±çŸ¥é“çš„æ‰˜ç®¡ä»“åº“
  - name: gitee
    url: https://gitee.com/
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/gitee.png
    description: ä¸­æ–‡ç‰ˆ"github",githubå®•æœºæ—¶å‘æŒ¥è‡³å…³é‡è¦çš„ä½œç”¨ï¼
  - name: coding
    url: https://coding.net/
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/coding.png
    description: æä¾›å…è´¹çš„ä»£ç é¡¹ç›®æ‰˜ç®¡ï¼ŒçœŸé¦™ï¼
  - name: Vercel
    url: https://vercel.com/
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/vercel.png
    description: æä¾›å…è´¹çš„ä»£ç é¡¹ç›®æ‰˜ç®¡ï¼ŒçœŸé¦™ï¼
  - name: GimhoyéŸ³ä¹ç›˜
    url: https://music.gimhoy.com/
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/gimhoy.png
    description: ä¸Šä¼ éŸ³ä¹ç”Ÿæˆå¤–è”ï¼Œåšå®¢å¼€å‘å¿…å¤‡å·¥å…·
  - name: èœé¸Ÿå·¥å…·
    url: https://c.runoob.com/
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/crunoob.ico
    description: å„ç§ç¼–ç¨‹å·¥å…·
  - name: mvnrepository
    url: https://mvnrepository.com/
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/mvnrepository.png
    description: mvn ä»“åº“
  - name: oschina tool
    url: https://tool.oschina.net/diff/
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/oschinatool.svg
    description: ä»£ç å¯¹æ¯”
  - name: Code Beautify
    url: https://codebeautify.org/
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/codebeautify.webp
    description: ä»£ç æ ¼å¼ç¾åŒ–
  - name: BEJSON
    url: https://www.bejson.com/convert/filesize/
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/bejson.png
    description: å•ä½æ¢ç®—


oj:
  - name: leetcode
    url: https://leetcode-cn.com/
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/leetcode.png
    description: å…¨çƒæå®¢æŒšçˆ±çš„æŠ€æœ¯æˆé•¿å¹³å°
  - name: ç‰›å®¢oj
    url: https://ac.nowcoder.com/acm/contest/vip-index
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/nowcoder.png
    description: ä¸“ä¸šçš„ç¼–ç¨‹ç®—æ³•è®­ç»ƒå¹³å°ï¼ŒåŒ…æ‹¬ACMæ ¡èµ›ã€ICPCã€CCPCã€CSPã€ä¿¡æ¯å­¦çœé€‰ã€NOIç­‰ç¼–ç¨‹æ¯”èµ›æé«˜è®­ç»ƒè¥
  - name: æ´›è°·
    url: https://www.luogu.com.cn/
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/luogu.png
    description: è‡´åŠ›äºä¸ºå‚åŠ noipã€noiã€acmçš„é€‰æ‰‹æä¾›æ¸…çˆ½ã€å¿«æ·çš„ç¼–ç¨‹ä½“éªŒ
  - name: new online judge
    url: http://oj.ecustacm.cn/
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/ecustacm.png
    description: ä¸“ä¸šçš„ç¼–ç¨‹ç®—æ³•è®­ç»ƒå¹³å°ï¼ŒåŒ…æ‹¬ACMæ ¡èµ›ã€ICPCã€CCPCã€CSPã€ä¿¡æ¯å­¦çœé€‰ã€NOIç­‰ç¼–ç¨‹æ¯”èµ›æé«˜è®­ç»ƒè¥
  - name: codeforces
    url: https://codeforces.com/
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/codeforces.png
    description: ojç‰ˆ"ç©¿è¶Šç«çº¿"ï¼Œæˆ‘çœ‹ä»Šå¤©æ™šä¸Šå°±æ˜¯ä¸Šåˆ†å‰æ—¥ï¼
  - name: PTA
    url: https://pintia.cn/
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/pintia.png
    description: ç¨‹åºè®¾è®¡ç±»å®éªŒè¾…åŠ©æ•™å­¦å¹³å°
  - name: ccf cspé¢˜åº“
    url: http://118.190.20.162/home.page
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/ccfcsp.png
    description: å„å¤§é«˜æ ¡è€ƒç ”å…æœºè¯•è€ƒæ ¸è®¤è¯



blog:
  - name: Google Search Console
    url: https://search.google.com/search-console
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/googlelogo.svg
    description: Google ç«™é•¿å¹³å°
  - name: æµ‹é€Ÿç½‘ç«™
    url: https://ping.chinaz.com/
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/ping.png
    description: å¿«é€Ÿæµ‹è¯•ç½‘ç«™åŠ è½½é€Ÿåº¦ï¼Œpingè¿é€šæ€§ç­‰æŒ‡æ ‡
  - name: Baidu Console
    url: https://ziyuan.baidu.com/dashboard
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/baidu.ico
    description: ç™¾åº¦ç«™é•¿å¹³å°
  - name: é˜¿é‡Œäº‘
    url: https://cn.aliyun.com/
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/aliyun.png
    description: äº‘æœåŠ¡å½“ç„¶æ˜¯æ”¶è´¹çš„ï¼Œæœ‰æ—¶éœ€è¦è´§æ¯”ä¸‰å®¶ï¼
  - name: åˆæ‹äº‘
    url: https://www.upyun.com/
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/youpaiyun.png
    description: äº‘æœåŠ¡å½“ç„¶æ˜¯æ”¶è´¹çš„ï¼Œæœ‰æ—¶éœ€è¦è´§æ¯”ä¸‰å®¶ï¼
  - name: Loading.io
    url: https://loading.io/
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/loadingio.ico
    description: loading å›¾ç‰‡ç”Ÿæˆ
  - name: PNG è½¬ SVG
    url: https://www.aconvert.com/cn/image/png-to-svg/#
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/aconvert.ico
    description: å›¾ç‰‡æ ¼å¼è½¬æ¢
  - name: footeræ‡’è®¾è®¡
    url: https://www.fotor.com.cn/
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/footer.png
    description: ä¸ºä½ çš„åšæ–‡è®¾è®¡ä¸€å¼ ç²¾ç¾çš„å¤´å›¾
  - name: å¯ç”»è®¾è®¡
    url: https://www.canva.cn/
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/canva.png
    description: ä¸ºä½ çš„åšæ–‡è®¾è®¡ä¸€å¼ ç²¾ç¾çš„å¤´å›¾


open-warehouse:
  - name: fontawesomeå›¾æ ‡åº“
    url: http://fontawesomelib.cn/releases/5.15.3/icon/books/duotone.html
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/fontawesomelib.png
    description: å…¨ä¸–ç•Œæœ€æµè¡Œçš„çŸ¢é‡å›¾æ ‡åº“
  - name: iconfont-é˜¿é‡Œå·´å·´çŸ¢é‡å›¾æ ‡åº“
    url: https://www.iconfont.cn/
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/iconfont.png
    description: å›½äº§å›¾æ ‡åº“çš„éª„å‚²ï¼
  - name: boxiconsçŸ¢é‡å›¾æ ‡åº“
    url:  https://boxicons.com/
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/boxicons.png
    description: è™½ç„¶å°ä¼—ï¼Œä½†æ˜¯å¾ˆæ¼‚äº®ï¼
  - name: emojiè¡¨æƒ…åŒ…
    url: http://www.fhdq.net/emoji/emojifuhao.html
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/emoji.png
    description: å…¨ä¸–ç•Œæœ€æµè¡Œçš„è¡¨æƒ…åŒ…
  - name: echartså›¾æ ‡åº“
    url: https://echarts.apache.org/zh/index.html
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/echarts.png
    description: ä¸€ä¸ªåŸºäº JavaScript çš„å¼€æºå¯è§†åŒ–å›¾è¡¨åº“ï¼Œæ•°æ®å±•ç¤ºå¿…å¤‡
  - name: emoji-cheat-sheet
    url: https://github.com/ikatyang/emoji-cheat-sheet/blob/master/README.md
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/emoji.png
    description: å¯ç›´æ¥å°†å›¾æ ‡å¤åˆ¶åˆ° hexo ä¸­ä½¿ç”¨


# ====================================== å¸¸ç”¨å·¥å…· ======================================

books:
  - name: èœé¸Ÿæ•™ç¨‹
    url: https://www.runoob.com/
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/cainiao.png
    description: æ‰€æœ‰å¼€å‘æŠ€æœ¯å‡å¯ä»¥åœ¨è¿™é‡Œå­¦ä¹ ,å­¦çš„ä¸ä»…æ˜¯æŠ€æœ¯ï¼Œæ›´æ˜¯æ¢¦æƒ³ï¼
  - name: å»–é›ªå³°å®˜æ–¹æ•™ç¨‹
    url: https://www.liaoxuefeng.com/
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/liaoxuefeng.png
    description: è·Ÿç€å¤§ç‰›å»–è€å¸ˆç•…æ¸¸çŸ¥è¯†æµ·æ´‹ï¼
  - name: OI WIKI
    url: https://oi-wiki.org/
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/oiwiki.png
    description: ACMerå¤§ä½¬çš„ç®—æ³•æ•™ç¨‹,èœé¸Ÿå¿…çœ‹ï¼


imagebeds: 
  - name: èšåˆå›¾åºŠ
    url: https://www.superbed.cn/
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/superbed.ico
    description: ç«™é•¿å¼ºçƒˆæ¨èä½¿ç”¨çš„é•¿æœŸæœ‰æ•ˆä¸”å…è´¹æ— é™å­˜å‚¨å›¾åºŠ
  - name: smmså›¾åºŠ
    url: https://sm.ms/
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/superbed.ico
    description: å›½å¤–å¼ºæ¨å®‰å…¨æ€§æå¼ºçš„å›¾åºŠç½‘ç«™ï¼Œä½†æ˜¯è¶…é™æ”¶è´¹
  - name: å»ä¸å›¾åºŠ
    url: https://7bu.top/
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/superbed.ico
    description: è€ç‰Œå…è´¹å›¾åºŠç½‘ç«™ï¼Œå€¼çš„ä¿¡èµ–ï¼
  - name: imgURLå…è´¹å›¾åºŠ
    url: https://imgurl.org/
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/superbed.ico
    description: è€ç‰Œå…è´¹å›¾åºŠç½‘ç«™ï¼Œå€¼çš„ä¿¡èµ–ï¼

files:
  - name: è½¬æ¢æˆpdf
    url: https://smallpdf.com/cn/pdf-converter
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/samllpdf.png
    description: smallpdfæä¾›æŠ€æœ¯æ”¯æŒï¼Œä½†æ˜¯ä¸€å¤©åªèƒ½å…è´¹ä½¿ç”¨2æ¬¡
  - name: å›¾ç‰‡å‹ç¼©
    url: https://www.tutieshi.com/compress/
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/tutieshi.png
    description: å›¾è´´å£«æä¾›æŠ€æœ¯æ”¯æŒï¼Œå…è´¹æ— é™åˆ¶ä½¿ç”¨
  - name: æ¶ˆé™¤èƒŒæ™¯
    url: https://www.remove.bg/zh/upload
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/removebg.png
    description: è¿…é€Ÿå»é™¤å›¾ç‰‡èƒŒæ™¯
  - name: docsmall
    url: https://docsmall.com/
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/docsmall.png
    description: åŒ…å«å¯¹å›¾ç‰‡çš„å„ç§å¸¸ç”¨å¤„ç†
  - name: Tinypng
    url: https://tinypng.com/
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/tinypng.ico
    description: å›¾ç‰‡æ— æŸå‹ç¼©
  - name: carbon
    url: https://carbon.now.sh/
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/carbon.ico
    description: Create and share beautiful images of your source code.
  - name: ç½‘é¡µç¼©ç•¥å›¾
    url: http://s.zcjun.com/
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/zcjun.png
    description: åœ¨çº¿ç”Ÿæˆç½‘é¡µé¢„è§ˆç¼©ç•¥å›¾



tools:
  - name: é¸ æ‘©æœä¹¦
    url: https://www.jiumodiary.com/
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/jiumodiary.png
    description: ç™½å«–æµ·é‡å›¾ä¹¦å¿…å¤‡ç½‘ç«™
  - name: äººäººæ–‡åº“
    url: https://www.renrendoc.com/
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/renrendoc.png
    description: ç™½å«–æµ·é‡å›¾ä¹¦å¿…å¤‡ç½‘ç«™
  - name: ç›˜å¤šå¤š
    url: https://www.panduoduo.org/dm/
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/panduoduo.png
    description: å…¨ç½‘å…è´¹èµ„æºæœç´¢ä¸‹è½½
  - name: æ¸¸ä¾ ç½‘
    url: https://www.ali213.net/
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/ali213.png
    description: å…è´¹ä¸‹è½½å•æœºæ¸¸æˆï¼Œä½†æ˜¯å«æœ‰å¤§é‡å¹¿å‘Š
  - name: å¾çˆ±ç ´è§£
    url: https://www.52pojie.cn/
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/52pojie.png
    description: ç”±ä¼—å¤šçƒ­è¡·äºè½¯ä»¶åŠ å¯†è§£å¯†åŠåç—…æ¯’çˆ±å¥½è€…å…±åŒç»´æŠ¤ï¼Œç•™ç»™ä¸–ç•Œä¸€æŠ¹å€¼å¾—ç™¾å¹´å›çœ¸çš„æƒŠè‰³
  - name: AGEåŠ¨æ¼«
    url: http://agefans.top/
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/agefans.png
    description: å…è´¹è§‚çœ‹åŠ¨æ¼«ç½‘ç«™
  - name: å½±è§†å¤§å…
    url: http://xinxx.cn/app/index.html?id=9999
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/xinxx.png
    description: æµ·é‡å½±è§†èµ„æºåˆ†äº«ï¼Œä½¿ç”¨ç™¾åº¦ç½‘ç›˜ä¸‹è½½
  - name: Sabrina çš„ä¸‡äº‹å±‹
    url: https://xclient.info/
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/xclient.ico
    description: âœˆï¸æœºåœºæ­å»º
  - name: Xclient
    url: https://merlinblog.xyz/
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/merlinblog.ico
    description: ç²¾å“MACåº”ç”¨åˆ†äº«
  - name: macwk
    url: https://macwk.com/
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/macwk.ico
    description: ç²¾å“MACåº”ç”¨ä¸‹è½½
  - name: keybr
    url: https://www.keybr.com/
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/keybr.png
    description: æ‰“å­—ç»ƒä¹ 
  - name: typingclub
    url: https://www.typingclub.com/
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/keybr.png
    description: typingclub æ‰“å­—ç»ƒä¹ 

# ====================================== è®¾è®¡ç¾åŒ– ======================================

colors:
  - name: Material Paletteé…è‰²æ¨è
    url: https://www.materialpalette.com/
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/materialpalette.png
    description: æä¾›ä¸°å¯Œçš„é¢œè‰²æ­é…è®¾è®¡åŒæ—¶è¿˜æä¾›icon
  - name: flatuicolorpické…è‰²æ¨è
    url: https://www.flatuicolorpicker.com/
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/flatuicolorpicker.png
    description: ä¸ºæ¯ä¸€ä¸ªä¸»è‰²éƒ½æä¾›åä¸ªä»¥ä¸Šçš„é¢œè‰²è®¾è®¡ä»£ç 
  - name: flatuicolorsé…è‰²æ¨è
    url: https://flatuicolors.com/
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/flatuicolors.png
    description: æä¾›å¤šå¥—å®Œæ•´çš„é…è‰²æ­é…ç³»
  - name: å°å½±é¢œè‰²æ­é…å·¥å…·ç®±
    url: http://tool.c7sky.com/webcolor/
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/c7sky.png
    description: æä¾›å¥½çœ‹çš„ä¸‰è‰²ä¸»è‰²ç³»æ­é…æ–¹æ¡ˆ
  - name: coolors
    url: https://coolors.co/
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/coolors.png
    description: coolors.co
  - name: RGB é¢œè‰²å€¼
    url: https://www.sioe.cn/yingyong/yanse-rgb-16/
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/sioe.ico
    description: RGBé¢œè‰²å€¼ä¸åå…­è¿›åˆ¶é¢œè‰²ç è½¬æ¢å·¥å…·


images:
  - name: Lorem Picsumå›¾ç‰‡å¿«é€Ÿç”Ÿæˆ
    url: https://picsum.photos/
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/picsum.png
    description: ç›´æ¥åŠ å…¥å›¾ç‰‡é«˜å®½ä»¥åŠrandomåºå·å³å¯è¿…é€Ÿç”Ÿæˆéšæœºå›¾ç‰‡
  - name: WALLPAPER
    url: https://wall.alphacoders.com/
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/alphacoders.png
    description: ç²¾ç¾é«˜æ¸…4kæ¡Œé¢å£çº¸æä¾›
  - name: 500PX
    url: https://500px.com.cn/
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/500px.ico
    description: è§†è§‰meè®¾è®¡ç¤¾åŒº
  - name: unsplash
    url: https://unsplash.com/
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/unsplash.png
    description: é«˜è´¨é‡å›¾ç‰‡ç½‘ç«™
  - name: WALLPAPER
    url: https://www.pixel4k.com/
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/cdn@main/navigation/img/pixel4k.ico
    description: ç²¾ç¾é«˜æ¸…4k



about:
  url: /about/
  icon: far fa-heart
  name: å…³äºæœ¬ç«™

aboutPage:
  website:
    head: å…³äºæœ¬ç«™
    html: '<blockquote><p>æœ¬ç«™æ˜¯ç”±<a href="https://yanliang.cool">Yanliang</a>åŸºäºhexoä¸»é¢˜<a href="https://github.com/HCLonely/hexo-theme-webstack">hexo-theme-webstack</a>åˆ›å»ºçš„ç½‘å€æ”¶è—ç™¾å®ç®±ã€‚</p></blockquote>'
  webmaster:
    head: å…³äºç«™é•¿
    name: yanliang
    url: https://yanliang.cool/
    img: https://cdn.jsdelivr.net/gh/gaoyanliang/blogImgs@main/blog/img/index-head.png
    description: é¢‘ç¹è®°å½•ï¼Œåªå› ç”Ÿæ´»å’Œä½ å¤ªå€¼å¾—â¤
    html: '<br /><blockquote><p>å¦‚æœå–œæ¬¢æ­¤ç½‘ç«™ï¼Œä¸å¦‚ <kbd>Ctrl</kbd> + <kbd>D</kbd> æ”¶è—ä¸€ä¸‹ï¼Ÿ</p></blockquote>'

since: 2020

busuanzi:
  enable: true
  position: sidebar # 'footer','sidebar'
  pv: æœ¬ç«™æ€»è®¿é—®é‡$pv
  uv: æœ¬ç«™æ€»è®¿å®¢æ•°$uv

custom:
  head: |- # ä»¥ä¸‹å†…å®¹æ’å…¥åˆ°<head></head>æ ‡ç­¾å†…ï¼Œå¯è®¾ç½®å¤šè¡Œï¼Œæ³¨æ„æ¯è¡Œå¼€å¤´è‡³å°‘å››ä¸ªç©ºæ ¼
    <!-- ç›´æ¥æ·»åŠ htmlå†…å®¹å³å¯ -->
    <!-- å¯è®¾ç½®å¤šè¡Œ -->
  body: |- # ä»¥ä¸‹å†…å®¹æ’å…¥åˆ°</body>æ ‡ç­¾ä¹‹å‰ï¼Œå¯è®¾ç½®å¤šè¡Œï¼Œæ³¨æ„æ¯è¡Œå¼€å¤´è‡³å°‘å››ä¸ªç©ºæ ¼
    <!-- ç›´æ¥æ·»åŠ htmlå†…å®¹å³å¯ -->
    <!-- å¯è®¾ç½®å¤šè¡Œ -->

js:
  header: /js/header.js
  footer: /js/footer.js
  jquery: /js/jquery-1.11.1.min.js
  bootstrap: /js/bootstrap.min.js
  TweenMax: /js/TweenMax.min.js
  resizeable: /js/resizeable.min.js
  joinable: /js/joinable.js
  xenonApi: /js/xenon-api.min.js
  xenonToggles: /js/xenon-toggles.min.js
  xenonCustom: /js/xenon-custom.min.js
  lozad: /js/lozad.min.js
  html5shiv: /js/html5shiv.min.js
  respond: /js/respond.min.js
  busuanzi: https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js

css:
  hclonely: /css/hclonely.css
  fonts: //fonts.loli.net/css?family=Arimo:400,700,400italic
  linecons: /css/fonts/linecons/css/linecons.min.css
  fontawesome: /css/fonts/fontawesome/css/all.min.css
  bootstrap: /css/bootstrap.min.css
  xenonCore: /css/xenon-core.min.css
  xenonComponents: /css/xenon-components.min.css
  xenonSkins: /css/xenon-skins.min.css
  nav: /css/nav.min.css
